### ISSUE TITLE
Blender 3.0.0 Error, MagicaVoxel-0.99.7.0-win64

### ISSUE THREAD

**Issue by Gosha-say** [RichysHub/MagicaVoxel-VOX-importer#22]
Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_scene_vox.py", line 126, in execute
    import_vox(path, **keywords)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_scene_vox.py", line 180, in import_vox
    assert (struct.unpack('<4ci', vox.read(8)) == (b'V', b'O', b'X', b' ', 150))
AssertionError

location: <unknown location>:-1

**Comment by dustinspace** [comment]
for me the same :-(

If you can tell me how to debug the Blender Pyton files I would be glad to help correcting the errors. I have some python background but I have no knowledge on which tools/methods are better suited for debugging, in case of Blender scripts.

thanks.

**Comment by dustinspace** [comment]
the error occurs because there is a newer version of the VOX files, and the importer is not up-to-date.
I did create a PullReq, which solves (partially) the problem.
You could be able to read the first model in the project correctly.
